/* =====================================================================
   Customer Shopping Behaviour Analysis: SQL Queries (PostgreSQL)
   ---------------------------------------------------------------------
   Business question:
     How can the company leverage consumer shopping data to identify
     trends, improve customer engagement, and optimize marketing and
     product strategies?

   Database : customer_behaviour
   Table    : customer (3,900 rows, one row per customer)
              Created and loaded by the Python notebook
              (Customer_Shopping_Behaviour_Analysis.ipynb, Section 8).

   How to run:
     Open this file in the pgAdmin Query Tool while connected to the
     database above. Run the whole file, or highlight one query and
     press F5 to run it on its own.
   ===================================================================== */


-- =====================================================================
-- Q1. What is the total revenue generated by male vs. female customers?
-- =====================================================================
SELECT gender,
       SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender
ORDER BY revenue DESC;


-- =====================================================================
-- Q2. Which customers used a discount but still spent more than the
--     average purchase amount?
-- =====================================================================
-- The subquery calculates the average purchase amount across all customers.
SELECT customer_id,
       purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer);


-- =====================================================================
-- Q3. Which are the top 5 products with the highest average review rating?
-- =====================================================================
-- review_rating is stored as double precision, so it is cast to numeric
-- because ROUND(value, 2) only works on numeric values in PostgreSQL.
SELECT item_purchased,
       ROUND(AVG(review_rating::numeric), 2) AS avg_product_rating
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;


-- =====================================================================
-- Q4. Compare the average purchase amount between Standard and Express
--     shipping.
-- =====================================================================
SELECT shipping_type,
       ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type
ORDER BY avg_purchase_amount DESC;


-- =====================================================================
-- Q5. Do subscribed customers spend more? Compare average spend and total
--     revenue between subscribers and non-subscribers.
-- =====================================================================
SELECT subscription_status,
       COUNT(customer_id)             AS total_customers,
       ROUND(AVG(purchase_amount), 2) AS avg_spend,
       ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;


-- =====================================================================
-- Q6. Which 5 products have the highest percentage of purchases with
--     discounts applied?
-- =====================================================================
-- CASE turns each discounted purchase into 1 (otherwise 0). The sum of
-- those values divided by the total purchases gives the discount rate.
-- Multiplying by 100.0 (not 100) avoids integer division.
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)
             / COUNT(*), 2) AS discount_rate_pct
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate_pct DESC
LIMIT 5;


-- =====================================================================
-- Q7. Segment customers into New, Returning, and Loyal based on their
--     number of previous purchases, and show the count of each segment.
-- =====================================================================
-- Segment rules:
--   New       = exactly 1 previous purchase
--   Returning = 2 to 10 previous purchases
--   Loyal     = more than 10 previous purchases
WITH customer_type AS (
    SELECT customer_id,
           previous_purchases,
           CASE
               WHEN previous_purchases = 1 THEN 'New'
               WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
               ELSE 'Loyal'
           END AS customer_segment
    FROM customer
)
SELECT customer_segment,
       COUNT(*) AS total_customers
FROM customer_type
GROUP BY customer_segment
ORDER BY total_customers DESC;


-- =====================================================================
-- Q8. What are the top 3 most purchased products within each category?
-- =====================================================================
-- ROW_NUMBER() ranks products inside each category by number of orders.
-- If two products have the same number of orders, they are ranked
-- alphabetically so the result is the same every time the query runs.
-- Note: Outerwear only has 2 products (Jacket, Coat), so the query
-- returns 11 rows instead of 12.
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (
               PARTITION BY category
               ORDER BY COUNT(customer_id) DESC, item_purchased
           ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,
       category,
       item_purchased,
       total_orders
FROM item_counts
WHERE item_rank <= 3
ORDER BY category, item_rank;


-- =====================================================================
-- Q9. Are repeat buyers (more than 5 previous purchases) also likely to
--     subscribe?
-- =====================================================================
-- pct_of_repeat_buyers shows each status as a share of all repeat buyers.
-- SUM(COUNT(customer_id)) OVER () is the total number of repeat buyers.
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers,
       ROUND(100.0 * COUNT(customer_id) / SUM(COUNT(customer_id)) OVER (), 2)
           AS pct_of_repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status
ORDER BY repeat_buyers DESC;


-- =====================================================================
-- Q10. What is the revenue contribution of each age group?
-- =====================================================================
-- age_group was created in the Python notebook using age quartiles:
--   Young Adult (18-31), Adult (32-44), Middle-aged (45-57), Senior (58-70)
SELECT age_group,
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
